metawards_kextendedLHC.html: metawards_kextendedLHC.Rmd
	Rscript -e 'knitr::knit("metawards_kextendedLHC.Rmd")'; \
	Rscript -e 'rmarkdown::render("metawards_kextendedLHC.md")'

metawards_plot.md: metawards_plot.Rmd
	Rscript -e 'knitr::knit("metawards_plot.Rmd")'

metawards_sa.md: metawards_sa.Rmd
	Rscript -e 'knitr::knit("metawards_sa.Rmd")'


